from ctypes import ( c_int, c_int64,
					 c_uint, c_uint8, c_uint16, c_uint32, c_uint64,
					 c_float,
                     c_void_p, c_char_p,
					 CFUNCTYPE, POINTER, Structure )
from .frame import AVFrame, AV_NUM_DATA_POINTERS
from .util import AVClass
from .buffer import AVBufferRef
from .rational import AVRational

class AVCodec(Structure):
    _fields_ = [
        ('name', c_char_p),
        ('long_name', c_char_p),
        ('type', c_int),
        ('id', c_int),
        ('capabilities', c_int),
        ('supported_framerates', POINTER(AVRational)),
        ('pix_fmts', POINTER(c_int)),
        ('supported_samplerates', POINTER(c_int)),
        ('sample_fmts', POINTER(c_int)),
        ('channel_layouts', POINTER(c_uint64)),
        ('max_lowres', c_uint8),
    ]

class AVCodecParameters(Structure):
    _fields_ = [
        ('codec_type', c_int),
        ('codec_id', c_int),
        ('codec_tag', c_uint32),
        ('extradata', POINTER(c_uint8)),
        ('extradata_size', c_int),
        ('format', c_int),
        ('bit_rate', c_int64),
        ('bits_per_coded_sample', c_int),
        ('bits_per_raw_sample', c_int),
        ('profile', c_int),
        ('level', c_int),
        ('width', c_int),
        ('height', c_int),
        ('sample_aspect_ratio', AVRational),
        ('field_order', c_int),
        ('color_range', c_int),
        ('color_primaries', c_int),
        ('color_trc', c_int),
        ('color_space', c_int),
        ('chroma_location', c_int),
        ('video_delay', c_int),
        ('channel_layout', c_uint64),
        ('channels', c_int),
        ('sample_rate', c_int),
        ('block_align', c_int),
        ('frame_size', c_int),
        ('initial_padding', c_int),
        ('trailing_padding', c_int),
        ('seek_preroll', c_int),
    ]

class AVCodecParserContext(Structure): pass   

class AVPacketSideData(Structure):
    _fields_ = [
        ('data', POINTER(c_uint8)),
        ('size', c_int),
        ('type', c_int)
    ]
    
class AVPacket(Structure):
    _fields_ = [
        ('buf', POINTER(AVBufferRef)),
        ('pts', c_int64),
        ('dts', c_int64),
        ('data', POINTER(c_uint8)),
        ('size', c_int),
        ('stream_index', c_int),
        ('flags', c_int),
        ('side_data', POINTER(AVPacketSideData)),
        ('side_data_elems', c_int),
        ('duration', c_int64),
        ('pos', c_int64),
        ('convergence_duration', c_int64) #Deprecated
    ]
    
class AVProfile(Structure):
    _fields_ = [
        ('profile', c_int),
        ('name', c_char_p),
    ]
class AVCodecDescriptor(Structure):
    _fields_ = [
        ('id', c_int),
        ('type', c_int),
        ('name', c_char_p),
        ('long_name', c_char_p),
        ('props', c_int),
        ('mime_types', c_char_p),
        ('profiles', POINTER(AVProfile))
    ]
    
class AVCodecInternal(Structure): pass

class RcOverride(Structure): pass

class AVHWAccel(Structure): pass

class AVCodecContext(Structure): pass 
AVCodecContext._fields_ = [
        ('av_class', POINTER(AVClass)),
        ('log_level_offset', c_int),
        ('codec_type', c_int),
        ('codec', POINTER(AVCodec)),
        ('codec_id', c_int),
        ('codec_tag', c_uint),
        ('priv_data', c_void_p),
        ('internal', POINTER(AVCodecInternal)),
        ('opaque', c_void_p),
        ('bit_rate', c_int64),
        ('bit_rate_tolerance', c_int),
        ('global_quality', c_int),
        ('compression_level', c_int),
        ('flags', c_int),
        ('flags2', c_int),
        ('extradata', POINTER(c_uint8)),
        ('extradata_size', c_int),
        ('time_base', AVRational),
        ('ticks_per_frame', c_int),
        ('delay', c_int),
        ('width', c_int),
        ('height', c_int),
        ('coded_width', c_int),
        ('coded_height', c_int),
        ('gop_size', c_int),
        ('pix_fmt', c_int),
        ('draw_horiz_band', CFUNCTYPE( None,
                                       POINTER(AVCodecContext), 
                                       POINTER(AVFrame),
                                       c_int*8, 
                                       c_int, 
                                       c_int, 
                                       c_int )),
        ('get_format', CFUNCTYPE( c_int,
                                  POINTER(AVCodecContext), 
                                  POINTER(c_int) )),
        ('max_b_frames', c_int),
        ('b_quant_factor', c_float),
        ('b_quant_offset', c_float),
        ('has_b_frames', c_int),
        ('i_quant_factor', c_float),
        ('i_quant_offset', c_float),
        ('lumi_masking', c_float),
        ('temporal_cplx_masking', c_float),
        ('spatial_cplx_masking', c_float),
        ('p_masking', c_float),
        ('dark_masking', c_float),
        ('slice_count', c_int),
        ('slice_offset', POINTER(c_int)),
        ('sample_aspect_ratio', AVRational),
        ('me_cmp', c_int),
        ('me_sub_cmp', c_int),
        ('mb_cmp', c_int),
        ('ildct_cmp', c_int),
        ('dia_size', c_int),
        ('last_predictor_count', c_int),
        ('me_pre_cmp', c_int),
        ('pre_dia_size', c_int),
        ('me_subpel_quality', c_int),
        ('me_range', c_int),
        ('slice_flags', c_int),
        ('mb_decision', c_int),
        ('intra_matrix', POINTER(c_uint16)),
        ('inter_matrix', POINTER(c_uint16)),
        ('intra_dc_precision', c_int),
        ('skip_top', c_int),
        ('skip_bottom', c_int),
        ('mb_lmin', c_int),
        ('mb_lmax', c_int),
        ('bidir_refine', c_int),
        ('keyint_min', c_int),
        ('refs', c_int),
        ('mv0_threshold', c_int),
        ('color_primaries', c_int),
        ('color_trc', c_int),
        ('colorspace', c_int),
        ('color_range', c_int),
        ('chroma_sample_location', c_int),
        ('slices', c_int),
        ('field_order', c_int),
        ('sample_rate', c_int),
        ('channels', c_int),
        ('sample_fmt', c_int),
        ('frame_size', c_int),
        ('frame_number', c_int),
        ('block_align', c_int),
        ('cutoff', c_int),
        ('channel_layout', c_uint64),
        ('request_channel_layout', c_uint64),
        ('audio_service_type', c_int),
        ('request_sample_fmt', c_int),
        ('get_buffer2', CFUNCTYPE( c_int,
                                   POINTER(AVCodecContext), 
                                   POINTER(AVFrame), 
                                   c_int )),
        ('qcompress', c_float),
        ('qblur', c_float),
        ('qmin', c_int),
        ('qmax', c_int),
        ('max_qdiff', c_int),
        ('rc_buffer_size', c_int),
        ('rc_override_count', c_int),
        ('rc_override', POINTER(RcOverride)),
        ('rc_max_rate', c_int64),
        ('rc_min_rate', c_int64),
        ('rc_max_available_vbv_use', c_float),
        ('rc_min_vbv_overflow_use', c_float),
        ('rc_initial_buffer_occupancy', c_int),
        ('stats_out', c_char_p),
        ('stats_in', c_char_p),
        ('workaround_bugs', c_int),
        ('strict_std_compliance', c_int),
        ('error_concealment', c_int),
        ('debug', c_int),
        ('err_recognition', c_int),
        ('reordered_opaque', c_int64),
        ('hwaccel', POINTER(AVHWAccel)),
        ('hwaccel_context', c_void_p),
        ('error', c_uint64 * AV_NUM_DATA_POINTERS),
        ('dct_algo', c_int),
        ('idct_algo', c_int),
        ('bits_per_coded_sample', c_int),
        ('bits_per_raw_sample', c_int),
        ('lowres', c_int),
        ('thread_count', c_int),
        ('thread_type', c_int),
        ('active_thread_type', c_int),
        ('thread_safe_callbacks', c_int),
        ('execute', CFUNCTYPE( c_int,
                               POINTER(AVCodecContext), 
                               CFUNCTYPE( c_int, 
                                          POINTER(AVCodecContext), 
                                          c_void_p ),
                               c_void_p, 
                               c_int, 
                               c_int, 
                               c_int )),
        ('execute2', CFUNCTYPE( c_int,
                                POINTER(AVCodecContext), 
                                CFUNCTYPE( c_int, 
                                           POINTER(AVCodecContext), 
                                           c_void_p, 
                                           c_int, 
                                           c_int ),
                                c_void_p, 
                                c_int, 
                                c_int )),
        ('nsse_weight', c_int),
        ('profile', c_int),
        ('level', c_int),
        ('skip_loop_filter', c_int),
        ('skip_idct', c_int),
        ('skip_frame', c_int),
        ('subtitle_header', POINTER(c_uint8)),
        ('subtitle_header_size', c_int),
        ('initial_padding', c_int),
        ('framerate', AVRational),
        ('sw_pix_fmt', c_int),
        ('pkt_timebase', AVRational),
        ('codec_dexcriptor', AVCodecDescriptor),
        ('pts_correction_num_faulty_pts', c_int64),
        ('pts_correction_num_faulty_dts', c_int64),
        ('pts_correction_last_pts', c_int64),
        ('pts_correction_last_dts', c_int64),
        ('sub_charenc', c_char_p),
        ('sub_charenc_mode', c_int),
        ('skip_alpha', c_int),
        ('seek_preroll', c_int),
        ('debug_mv', c_int),
        ('chroma_intra_matrix', POINTER(c_uint16)),
        ('dump_separator', POINTER(c_uint8)),
        ('codec_whitelist', c_char_p),
        ('properties', c_uint),
        ('coded_side_data', POINTER(AVPacketSideData)),
        ('nb_coded_side_data', c_int),
        ('hw_frames_ctx', POINTER(AVBufferRef)),
        ('sub_text_format', c_int),
        ('trailing_padding', c_int),
        ('max_pixels', c_int64),
        ('hw_device_ctx', POINTER(AVBufferRef)),
        ('hwaccel_flags', c_int),
        ('apply_cropping', c_int),
        ('extra_hw_frames', c_int)
    ]
    
    