from .rational import AVRational

# Time
AV_TIME_BASE = 1000000
AV_TIME_BASE_Q = AVRational(1,AV_TIME_BASE)

# Media types
AVMEDIA_TYPE_UNKNOWN = -1
AVMEDIA_TYPE_VIDEO = 0
AVMEDIA_TYPE_AUDIO = 1
AVMEDIA_TYPE_DATA = 2
AVMEDIA_TYPE_SUBTITLE = 3, 
AVMEDIA_TYPE_ATTACHMENT = 4
AVMEDIA_TYPE_NB = 5

# Values
AV_PTS_EXACT = 1
AV_PTS_AVERAGE = 3
AV_NOPTS_VALUE = -9223372036854775808